apiVersion: v2
appVersion: 2.1.0
dependencies:
- condition: fluent-bit.enabled,sumologic.logs.enabled
  name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: 0.15.1
- condition: kube-prometheus-stack.enabled,sumologic.metrics.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 12.3.0
- condition: falco.enabled
  name: falco
  repository: https://falcosecurity.github.io/charts
  version: 1.7.10
- condition: metrics-server.enabled
  name: metrics-server
  repository: https://charts.bitnami.com/bitnami
  version: 5.8.1
- condition: telegraf-operator.enabled
  name: telegraf-operator
  repository: https://helm.influxdata.com/
  version: 1.1.5
- condition: tailing-sidecar-operator.enabled
  name: tailing-sidecar-operator
  repository: https://sumologic.github.io/tailing-sidecar
  version: 0.3.0
description: A Helm chart for collecting Kubernetes logs, metrics, traces and events into Sumo Logic.
home: https://github.com/SumoLogic/sumologic-kubernetes-collection
icon: https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/main/images/sumo_logic_logo.png
keywords:
- monitoring
- logging
name: sumologic
sources:
- https://github.com/SumoLogic/sumologic-kubernetes-collection
type: application
version: 2.1.0
