apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sumologiccollections.helm-operator.sumologic.com
spec:
  group: helm-operator.sumologic.com
  names:
    kind: SumologicCollection
    listKind: SumologicCollectionList
    plural: sumologiccollections
    singular: sumologiccollection
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SumologicCollection is the Schema for the sumologiccollections
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of SumologicCollection
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of SumologicCollection
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sumologic-leader-election-role
  namespace: sumologic-system
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - configmaps
  - deployments
  - daemonsets
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - helm-operator.sumologic.com
  resources:
  - sumologiccollections
  - sumologiccollections/status
  - sumologiccollections/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - daemonsets
  - endpoints
  - events
  - limitranges
  - lists
  - namespaces
  - nodes
  - nodes/metrics
  - nodes/stats
  - persistentvolumeclaims
  - persistentvolumes
  - persistentvolumeclaims/finalizers
  - persistentvolumes/finalizers
  - pods
  - pods/finalizers
  - pods/exec
  - pods/log
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - serviceaccounts
  - secrets
  - secrets/finalizers
  - services
  - secrets/finalizers
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - ingresses
  - namespaces
  - nodes
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - alertmanagers/finalizers
  - podmonitors
  - probes
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  - thanosrulers
  - thanosrulers/finalizers
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- nonResourceURLs:
  - /metrics/cadvisor
  - /metrics
  verbs:
  - get
- nonResourceURLs:
  - /healthz/*
  verbs:
  - get
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - '*'
- apiGroups:
  - tailing-sidecar.sumologic.com
  resources:
  - tailingsidecars
  - tailingsidecars/status
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sumologic-leader-election-rolebinding
  namespace: sumologic-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sumologic-leader-election-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumologic-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumologic-operator-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumologic-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumologic-proxy-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080

    leaderElection:
      leaderElect: true
      resourceName: 811c9dc5.sumologic.com
kind: ConfigMap
metadata:
  name: sumologic-operator-config
  namespace: sumologic-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-helm-operator-metrics-service
  namespace: sumologic-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: sumologic-kubernetes-collection-helm-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-helm-operator
  namespace: sumologic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: sumologic-kubernetes-collection-helm-operator
  template:
    metadata:
      labels:
        control-plane: sumologic-kubernetes-collection-helm-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: registry.connect.redhat.com/sumologic/kube-rbac-proxy:v0.5.0-ubi
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --leader-election-id=sumologic-kubernetes-collection-helm-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: sumologic-kubernetes-collection-helm-operator
        - name: RELATED_IMAGE_KUBERNETES_SETUP
          value: public.ecr.aws/sumologic/kubernetes-setup@sha256:767fd3505df5ca59fb502dfb1678f3d6e8cfac2d249972cc50d541939a7a2e31
        - name: RELATED_IMAGE_NODE_EXPORTER
          value: quay.io/prometheus/node-exporter@sha256:f2269e73124dd0f60a7d19a2ce1264d33d08a985aed0ee6b0b89d0be470592cd
        - name: RELATED_IMAGE_KUBE_STATE_METRICS
          value: k8s.gcr.io/kube-state-metrics/kube-state-metrics@sha256:47d3a12d9da6699a9d95df8aaff235305229ef08203fae3fc1f1d47b2a409f89
        - name: RELATED_IMAGE_PROMETHEUS_OPERATOR
          value: quay.io/prometheus-operator/prometheus-operator@sha256:983627001c89bc6d7d881939c0c314c72ee26256004e8890c9e31efc498d7649
        - name: RELATED_IMAGE_PROMETHEUS_CONFIG_RELOADER
          value: quay.io/prometheus-operator/prometheus-config-reloader@sha256:6659cb3d97b5f846b5e1651ca1ab95189509f899713c727143f1bc50cc6e57cf
        - name: RELATED_IMAGE_PROMETHEUS
          value: quay.io/prometheus/prometheus@sha256:b899dbd1b9017b9a379f76ce5b40eead01a62762c4f2057eacef945c3c22d210
        - name: RELATED_IMAGE_THANOS
          value: quay.io/thanos/thanos@sha256:43bfca02f322e4c719f4a373dd4618685fa806ce6d8094e1e2ff4a6ba4260cc2
        - name: RELATED_IMAGE_METRICS_SERVER
          value: docker.io/bitnami/metrics-server@sha256:579ed5377d14841c6b1641cfaf9c0802420a066529b8a71e5f91609d3f28fd05
        - name: RELATED_IMAGE_KUBE_RBAC_PROXY
          value: gcr.io/kubebuilder/kube-rbac-proxy@sha256:e10d1d982dd653db74ca87a1d1ad017bc5ef1aeb651bdea089debf16485b080b
        - name: RELATED_IMAGE_TAILING_SIDECAR_OPERATOR
          value: ghcr.io/sumologic/tailing-sidecar-operator@sha256:51438fd64b91ed2f4dcafec60aaa8b5f3098b1aa035b39d5931cd7987a0bdc4f
        - name: RELATED_IMAGE_TAILING_SIDECAR
          value: ghcr.io/sumologic/tailing-sidecar@sha256:4cd7efc6baf434805aab33a9ded476f4fd6195f7a8ed38be99179d1a99a9d3c0
        - name: RELATED_IMAGE_TELEGRAF_OPERATOR
          value: quay.io/influxdb/telegraf-operator@sha256:20af9e3715f24002a23d3759b451ede47061fb27761e244f69bbe742f7a502d0
        - name: RELATED_IMAGE_TELEGRAF
          value: public.ecr.aws/sumologic/telegraf@sha256:ab779faeb3a2bd480c3f235738091eb8880c4086c60774f50d1e950dd22d994a
        - name: RELATED_IMAGE_KUBERNETES_FLUENTD
          value: public.ecr.aws/sumologic/kubernetes-fluentd@sha256:a07ea5c9025a4ed4c964165fae961fef902645fc3eb741761ac5068b1684acce
        - name: RELATED_IMAGE_FLUENT_BIT
          value: public.ecr.aws/sumologic/fluent-bit@sha256:2861b8821e685873b1e806376bf50beb4326ed577a9882661ed7b849927d91cc
        - name: RELATED_IMAGE_OPENTELEMETRY_COLLECTOR
          value: public.ecr.aws/sumologic/sumologic-otel-collector:0.54.0-sumo-0@sha:sha256:b615e9e2cba4c3ec2d43146fcaf42dc132a0ba2d606933b1fa3324265991fac0
        - name: RELATED_IMAGE_OPENTELEMETRY_OPERATOR
          value: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator@sha256:148960f590a96fb000b2ff2accb33d131e52649006ef24a0c572664b8d2c9644
        image: registry.connect.redhat.com/sumologic/sumologic-kubernetes-collection-helm-operator:2.1.4-0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: sumologic-helm-operator
      terminationGracePeriodSeconds: 10
