apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sumologiccollections.helm-operator.sumologic.com
spec:
  group: helm-operator.sumologic.com
  names:
    kind: SumologicCollection
    listKind: SumologicCollectionList
    plural: sumologiccollections
    singular: sumologiccollection
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SumologicCollection is the Schema for the sumologiccollections
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of SumologicCollection
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of SumologicCollection
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sumologic-leader-election-role
  namespace: sumologic-system
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - configmaps
  - deployments
  - daemonsets
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - helm-operator.sumologic.com
  resources:
  - sumologiccollections
  - sumologiccollections/status
  - sumologiccollections/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - daemonsets
  - endpoints
  - events
  - limitranges
  - lists
  - namespaces
  - nodes
  - nodes/metrics
  - nodes/stats
  - persistentvolumeclaims
  - persistentvolumes
  - persistentvolumeclaims/finalizers
  - persistentvolumes/finalizers
  - pods
  - pods/finalizers
  - pods/exec
  - pods/log
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - serviceaccounts
  - secrets
  - secrets/finalizers
  - services
  - secrets/finalizers
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - ingresses
  - namespaces
  - nodes
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - alertmanagers/finalizers
  - podmonitors
  - probes
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  - thanosrulers
  - thanosrulers/finalizers
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- nonResourceURLs:
  - /metrics/cadvisor
  - /metrics
  verbs:
  - get
- nonResourceURLs:
  - /healthz/*
  verbs:
  - get
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - '*'
- apiGroups:
  - tailing-sidecar.sumologic.com
  resources:
  - tailingsidecars
  - tailingsidecars/status
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
- apiGroups:
  - opentelemetry.io
  resources:
  - instrumentations
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologic-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sumologic-leader-election-rolebinding
  namespace: sumologic-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sumologic-leader-election-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumologic-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumologic-operator-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumologic-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumologic-proxy-role
subjects:
- kind: ServiceAccount
  name: sumologic-helm-operator
  namespace: sumologic-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080

    leaderElection:
      leaderElect: true
      resourceName: 811c9dc5.sumologic.com
kind: ConfigMap
metadata:
  name: sumologic-operator-config
  namespace: sumologic-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-helm-operator-metrics-service
  namespace: sumologic-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: sumologic-kubernetes-collection-helm-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-helm-operator
  namespace: sumologic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: sumologic-kubernetes-collection-helm-operator
  template:
    metadata:
      labels:
        control-plane: sumologic-kubernetes-collection-helm-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: registry.connect.redhat.com/sumologic/kube-rbac-proxy:v0.8.0-ubi
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --leader-election-id=sumologic-kubernetes-collection-helm-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: sumologic-kubernetes-collection-helm-operator
        - name: RELATED_IMAGE_KUBERNETES_SETUP
          value: registry.connect.redhat.com/sumologic/kubernetes-setup@sha256:96de6f9352cabbddf7f0cb537108b41183e827be27d100ba6566bbb0d1c0f01d
        - name: RELATED_IMAGE_NODE_EXPORTER
          value: registry.connect.redhat.com/sumologic/node-exporter@sha256:7acec4473ddf508514dca1d08335cfd071e345d7eca660793d59e09ef9f0491f
        - name: RELATED_IMAGE_KUBE_STATE_METRICS
          value: registry.connect.redhat.com/sumologic/kube-state-metrics@sha256:094ad2a0136b7ded390763dd9c63acf282903d49d07385a806160e2cdad89345
        - name: RELATED_IMAGE_PROMETHEUS_OPERATOR
          value: registry.connect.redhat.com/sumologic/prometheus-operator@sha256:79769d200a6d5b977fed1c05e1021ad83b89b817b30ab24131cf9d262f4b86fc
        - name: RELATED_IMAGE_PROMETHEUS_CONFIG_RELOADER
          value: registry.connect.redhat.com/sumologic/prometheus-config-reloader@sha256:bbc4ae3f769172545cd0ee7862066e6dab75045370f099e4bdacc344fe7c46a7
        - name: RELATED_IMAGE_PROMETHEUS
          value: registry.connect.redhat.com/sumologic/prometheus@sha256:f9fa9040c8e134a1e6be81dd6e14f1d1dee3e0651e4039cf9580e8e9cfbf8455
        - name: RELATED_IMAGE_THANOS
          value: registry.connect.redhat.com/sumologic/thanos@sha256:9772a1f329596cc4f0934b044f63b2c4f6e93952a44f1c68cc09f1a61f7f309a
        - name: RELATED_IMAGE_METRICS_SERVER
          value: registry.connect.redhat.com/sumologic/metrics-server@sha256:4a60b5f706e4ae2b79c91a90dd4d23d8fd87408beed9f0a14a29d639bbcb8a35
        - name: RELATED_IMAGE_KUBE_RBAC_PROXY
          value: registry.connect.redhat.com/sumologic/kube-rbac-proxy@sha256:c1ea7aa4873a78d8d506e4dab8c281c6c72a65d1374312cd76b27ed881b043b5
        - name: RELATED_IMAGE_TAILING_SIDECAR_OPERATOR
          value: registry.connect.redhat.com/sumologic/tailing-sidecar-operator@sha256:8b22b5035e7512fff17b05b37076f1bdbc3102cfbfc676e66ef7f3682dff5b98
        - name: RELATED_IMAGE_TAILING_SIDECAR
          value: registry.connect.redhat.com/sumologic/tailing-sidecar@sha256:34c7e3d6a15dcbb72ce498744baa5e6b4663af4838a6f6429458e2d73ecb4d09
        - name: RELATED_IMAGE_TELEGRAF_OPERATOR
          value: registry.connect.redhat.com/sumologic/telegraf-operator@sha256:e27d7a4d7c9947685641df6e238fbae5a48993530bd5c2c4bf6d7385c262715e
        - name: RELATED_IMAGE_TELEGRAF
          value: registry.connect.redhat.com/sumologic/telegraf@sha256:ca396dad12a289aea9136da713020d31b179e9f49aae61c48332d61086d1d059
        - name: RELATED_IMAGE_KUBERNETES_FLUENTD
          value: registry.connect.redhat.com/sumologic/kubernetes-fluentd@sha256:fdc41e366fa24046eb023ab76ca3bb571cdde5b35ea75ccdd9b9435091266562
        - name: RELATED_IMAGE_FLUENT_BIT
          value: registry.connect.redhat.com/sumologic/fluent-bit@sha256:4e76cb20c8808ac149db6ba532ab3f42047e5a5e8d178a7294f9881d0bbf3f43
        - name: RELATED_IMAGE_SUMOLOGIC_OTEL_COLLECTOR
          value: registry.connect.redhat.com/sumologic/sumologic-otel-collector@sha256:9e37f8f6244f82a4caa138d77f89a946f781e76c74326b771727843cd9f113a1
        - name: RELATED_IMAGE_OPENTELEMETRY_OPERATOR
          value: registry.connect.redhat.com/sumologic/opentelemetry-operator@sha256:9f62a7e50ea91a2424fc48f94feff3ccfc4a1fccaabf56dd5259852ba2565efd
        image: registry.connect.redhat.com/sumologic/sumologic-kubernetes-collection-helm-operator:2.17.0-0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: sumologic-helm-operator
      terminationGracePeriodSeconds: 10
