apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        args:
        - "--config=controller_manager_config.yaml"
        volumeMounts:
        - name: operator-config
          mountPath: /controller_manager_config.yaml
          subPath: controller_manager_config.yaml
      volumes:
      - name: operator-config
        configMap:
          name: operator-config
