apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: sumologic-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: sumologic-kubernetes-collection-helm-operator
status:
  loadBalancer: {}
