apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - pods
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - services
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - events.k8s.io
  resources:
  - configmaps
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - events.k8s.io
  resources:
  - daemonsets
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - events.k8s.io
  resources:
  - deployments
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - configmaps
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - endpoints
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - events
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - namespaces
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - nodes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - daemonsets
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - deployments
- verbs:
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - replicasets
  - lists
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - statefulsets
  - limitranges
  - resourcequotas
  - replicationcontrollers
  - nodes/metrics
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - statefulsets
  - limitranges
  - resourcequotas
  - replicationcontrollers
  - nodes/metrics
- verbs:
  - get
  - create
  - describe
  - patch
  - list
  - delete
  - update
  - watch
  apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
- verbs:
  - get
  - create
  - describe
  - patch
  apiGroups:
  - ''
  resources:
  - secrets
  - namespaces
- verbs:
  - get
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - '*'
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - create
  apiGroups:
  - ''
  resources:
  - events
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - helm-operator.sumologic.com
  resources:
  - sumologiccollections
  - sumologiccollections/status
  - sumologiccollections/finalizers
- verbs:
  - '*'
  apiGroups:
  - route.openshift.io
  resources:
  - routes
- verbs:
  - '*'
  apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - nodes
  - events
  - secrets
  - secrets/finalizers
  - pods
  - pods/finalizers
  - serviceaccounts
  - services
  - configmaps
- verbs:
  - '*'
  apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
- verbs:
  - '*'
  apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
- verbs:
  - list
  - watch
  apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
- verbs:
  - use
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - ''
  resources:
  - secrets
  - secrets/finalizers
  - pods
  - pods/finalizers
  - pods/exec
  - pods/log
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - persistentvolumeclaims/finalizers
  - persistentvolumes/finalizers
  - nodes
  - events
  - configmaps
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - use
  apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  - apps
  - extensions
  - events.k8s.io
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
- verbs:
  - create
  - patch
  apiGroups:
  - ''
  resources:
  - configmaps
- verbs:
  - use
  apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - '*'
- verbs:
  - get
  - list
  - describe
  - delete
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - get
  - list
  - describe
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - "*"
  apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  - alertmanagers
  - alertmanagers/finalizers
  - podmonitors
  - probes
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  - thanosrulers
  - thanosrulers/finalizers
- verbs:
  - get
  - list
  - describe
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - list
  - watch
  apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
- verbs:
  - list
  - watch
  apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
- verbs:
  - list
  - watch
  apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
- verbs:
  - list
  - watch
  apiGroups:
  - extensions
  resources:
  - ingresses
- verbs:
  - watch
  apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
- verbs:
  - list
  - watch
  apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
- verbs:
  - use
  apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
- verbs:
  - get
  nonResourceURLs:
  - "/metrics/cadvisor"
  - "/metrics"

#+kubebuilder:scaffold:rules
