# permissions for end users to view sumologiccollections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumologiccollection-viewer-role
rules:
- apiGroups:
  - helm-operator.sumologic.com
  resources:
  - sumologiccollections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm-operator.sumologic.com
  resources:
  - sumologiccollections/status
  verbs:
  - get
