apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sumologic-kubernetes-collection-helm-operator
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Helm Operator for the Sumo Logic Kubernetes Collection Chart
  displayName: Sumo Logic Kubernetes Collection Helm Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - collection
  - logging
  - metrics
  - monitoring
  links:
  - name: Sumo Logic Kubernetes Collection Helm Operator
    url: https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator
  maintainers:
  - email: collection@sumologic.com
    name: Sumo Logic
  maturity: alpha
  provider:
    name: Sumo Logic
    url: https://www.sumologic.com/
  version: 0.0.0
