apiVersion: helm-operator.sumologic.com/v1alpha1
kind: SumologicCollection
metadata:
  name: collection
spec:
  ## Sumo Logic Kubernetes Collection configuration file
  ## All the comments start with two or more # characters

  sumologic:
    ## Sumo access ID
    accessId: ""

    ## Sumo access key
    accessKey: ""

    ## Collector name
    # collectorName: ""

    ## Cluster name: Note spaces are not allowed and will be replaced with dashes.
    clusterName: "kubernetes"

    ## creation of Security Context Constraints in Openshift
    scc:
      create: true

  ## Configure metrics-server
  ## ref: https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/values.yaml
  metrics-server:
    ## Set the enabled flag to true for enabling metrics-server.
    ## This is required before enabling autoscaling unless you have an existing metrics-server in the cluster.
    enabled: true
    apiService:
      create: false
    global:
      compatibility:
        ## Compatibility adaptations for Openshift
        ##
        openshift:
          ## @param global.compatibility.openshift.adaptSecurityContext Adapt the securityContext sections of the deployment to make them compatible with Openshift restricted-v2 SCC: remove runAsUser, runAsGroup and fsGroup and let the platform use their allowed default IDs. Possible values: auto (apply if the detected running cluster is Openshift), force (perform the adaptation always), disabled (do not perform adaptation)
          ##
          adaptSecurityContext: auto

  ## Configure kube-prometheus-stack
  ## ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  kube-prometheus-stack:
    prometheus-node-exporter:
      service:
        port: 9200
        targetPort: 9200
    prometheusOperator:
      enabled: true
      denyNamespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-machine-approver
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns,openshift-dns-operator
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-sdn
      - openshift-service-ca-operator
      - openshift-user-workload-monitoring

    prometheus:
      enabled: true

  ## Configure log collection with Otelcol
  otellogs:
    daemonset:
      containers:
        otelcol:
          securityContext:
            privileged: true
      initContainers:
        changeowner:
          securityContext:
            privileged: true

  ## Configure telegraf-operator
  ## ref: https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-operator/values.yaml
  telegraf-operator:
    enabled: true

  ## Configure Tailing Sidecar Operator
  ## ref: https://github.com/SumoLogic/tailing-sidecar/blob/main/helm/tailing-sidecar-operator/values.yaml
  tailing-sidecar-operator:
    enabled: true

    ## creation of Security Context Constraints in Openshift
    scc:
      create: true

  ## pvcCleaner deletes unused PVCs
  pvcCleaner:
    metrics:
      enabled: true
    logs:
      enabled: true
