apiVersion: helm-operator.sumologic.com/v1alpha1
kind: SumologicCollection
metadata:
  name: collection
spec:
  ## Sumo Logic Kubernetes Collection configuration file
  ## All the comments start with two or more # characters

  sumologic:
    ## Sumo access ID
    accessId: ""

    ## Sumo access key
    accessKey: ""

    ## Collector name
    # collectorName: ""

    ## Cluster name: Note spaces are not allowed and will be replaced with dashes.
    clusterName: "kubernetes"

    ## creation of Security Context Constraints in Openshift
    scc:
      create: true

  ## Configure kube-prometheus-stack
  ## ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  kube-prometheus-stack:
    prometheus-node-exporter:
      service:
        port: 9200
        targetPort: 9200

  ## Configure log collection with Otelcol
  otellogs:
    daemonset:
      containers:
        otelcol:
          securityContext:
            privileged: true
      initContainers:
        changeowner:
          securityContext:
            privileged: true
