---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sumologiccollections.helm-operator.sumologic.com
spec:
  group: helm-operator.sumologic.com
  names:
    kind: SumologicCollection
    listKind: SumologicCollectionList
    plural: sumologiccollections
    singular: sumologiccollection
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
