name: PRs checks

on:
  pull_request:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: |
            curl --retry 10 --retry-max-time 120 --retry-delay 5 -Lo- https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz | tar -xJf -
            sudo cp shellcheck-v0.7.1/shellcheck /usr/local/bin && rm -rf shellcheck-v0.7.1
      - name: shellcheck
        run: make shellcheck
      - name: Install pylint
        run: sudo apt-get install --yes pylint
      - name: Run pylint
        run: make pylint
        
  test-bundle-status:
    name: Test whether bundle.yaml is up to date
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check bundle.yaml
        run: make test-bundle-status

  test-helm-operator:
    name: Test Helm operator
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    env:
      IMG: sumologic/sumologic-kubernetes-helm-operator:test
    steps:
      - uses: actions/checkout@v2
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Install Helm in tested version
        run: |
          sudo mkdir /opt/helm3
          sudo curl "https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz" | tar -xz -C /opt/helm3
          sudo rm /usr/local/bin/helm
          sudo ln -s /opt/helm3/linux-amd64/helm /usr/bin/helm3
          sudo ln -s /usr/bin/helm3 /usr/bin/helm
          helm version
      - uses: imranismail/setup-kustomize@v1
      - uses: AbsaOSS/k3d-action@v2
        id: single-cluster
        name: Create single k3d Cluster
        with:
          cluster-name: "k3s-default"
          args: >-
            --agents 1
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: Checkout submodules
        run: git submodule update --init
      - name: Build helm operator image
        run: make docker-build IMG="${IMG}"
      - name: Import helm operator image to k3d
        run:  k3d image import sumologic/sumologic-kubernetes-helm-operator:test -c k3s-default --verbose
      - name: Test Helm operator
        run: make test-using-public-images IMG="${IMG}"
