name: PRs checks

on:
  pull_request:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

jobs:
  test-helm-operator:
    name: Test Helm operator
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    env:
      IMG: registry.localhost:5000/sumologic/sumologic-collection-helm-operator:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.8.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - uses: imranismail/setup-kustomize@v1
      - uses: AbsaOSS/k3d-action@v1.4.0
        id: single-cluster
        name: Create single k3d Cluster with Registry
        with:
          cluster-name: "test-cluster"
          use-default-registry: true
          args: >-
            --agents 1
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"
      - name: Checkout submodules
        run: git submodule update --init
      - name: Build helm operator image
        run: make docker-build IMG="${IMG}"
      - name: Push helm operator image to local registry
        run: make docker-push IMG="${IMG}"
      - name: Test Helm operator
        run: make test-using-public-images IMG="${IMG}"
